spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/liquibase_demo?verifyServerCertificate=false&useSSL=true'
    username: root
    password:
    platform: mysql
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none # Set to none let liquibase handle database schema
    open-in-view: false
